// Generates src/version.ts from package.json so the version lives in ONE place.
// Run automatically at the start of `bun run build`.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { execFileSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
let sourceRef = "main";
let inGit = false;
try {
  const dirty = execFileSync("git", ["status", "--porcelain", "--untracked-files=normal", "--", ".", ":(exclude)src/source-info.ts"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  inGit = true;
  if (!dirty) sourceRef = execFileSync("git", ["rev-parse", "HEAD"], { cwd: root, encoding: "utf8" }).trim();
} catch { /* npm source packages have no .git directory */ }
const repository = pkg.repository.url.replace(/\.git$/, "");
const sourceInfo = join(root, "src", "source-info.ts");
// A package rebuilt outside Git retains the release's supplied source link.
if (inGit || !existsSync(sourceInfo)) writeFileSync(sourceInfo,
  "// AUTO-GENERATED by scripts/sync-version.mjs.\n" +
  `export const SOURCE_URL = ${JSON.stringify(`${repository}/blob/${sourceRef}/SOURCE.md`)};\n`);
const body =
  "// AUTO-GENERATED from package.json by scripts/sync-version.mjs — do not edit by hand.\n" +
  `export const VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(join(root, "src", "version.ts"), body);
console.error(`[sync-version] src/version.ts → ${pkg.version}`);

const registryPath = join(root, "server.json");
const registry = JSON.parse(readFileSync(registryPath, "utf8"));
registry.version = pkg.version;
for (const entry of registry.packages ?? []) entry.version = pkg.version;
writeFileSync(registryPath, JSON.stringify(registry, null, 2) + "\n");

const kimiPluginPath = join(root, "kimi.plugin.json");
const kimiPlugin = JSON.parse(readFileSync(kimiPluginPath, "utf8"));
kimiPlugin.version = pkg.version;
kimiPlugin.license = pkg.license;
writeFileSync(kimiPluginPath, JSON.stringify(kimiPlugin, null, 2) + "\n");
